development:
  adapter: postgresql
  encoding: utf8
  database: recircle_development
  username: root
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: recircle_test
  username: root
